# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build-and-deploy:
  # This workflow contains a single job called "build"

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -name:Checkout
       uses: actions/checkout@v2
       
       -name: Configure Node
        uses: actions/setup-node@v1
        with:
           node-version: '12.18.4'
           
        -name:install
        run: |
          npm c1
          npm run build

      # Runs a single command using the runners shell
      #- name: Run a one-line script
     # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: ruchika2827/github-pages-deploy-act ion@v4
        with:
          folder: build
          branch: gh-pages
         # echo Add other actions to build,
          #echo test, and deploy your project.
